# Generated by Django 4.1.1 on 2022-10-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction", models.IntegerField()),
                ("date", models.DateField()),
                ("value", models.FloatField(max_length=10)),
                ("cpf", models.IntegerField(max_length=11)),
                ("card", models.IntegerField(max_length=12)),
                ("hour", models.TimeField()),
                ("owner", models.CharField(max_length=14)),
                ("store", models.CharField(max_length=19)),
            ],
        ),
    ]
