# Generated by Django 4.1.1 on 2022-10-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0002_alter_info_card"),
    ]

    operations = [
        migrations.AlterField(
            model_name="info",
            name="cpf",
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name="info",
            name="date",
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name="info",
            name="hour",
            field=models.CharField(max_length=6),
        ),
    ]
