# Generated by Django 4.1.1 on 2022-10-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction", models.CharField(max_length=20)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("value", models.IntegerField(max_length=10)),
                ("cpf", models.IntegerField(max_length=11)),
                ("card", models.IntegerField(max_length=12)),
                ("time", models.TimeField(auto_now_add=True)),
                ("owner", models.CharField(max_length=14)),
                ("store", models.CharField(max_length=19)),
            ],
        ),
    ]
